"""Add alerts model

Revision ID: b2288ac7ab27
Revises: b9f283807a16
Create Date: 2026-01-04 17:22:38.468464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2288ac7ab27'
down_revision = 'b9f283807a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_transfers_dates'))
        batch_op.drop_index(batch_op.f('idx_transfers_from_warehouse'))
        batch_op.drop_index(batch_op.f('idx_transfers_product_id'))
        batch_op.drop_index(batch_op.f('idx_transfers_status'))
        batch_op.drop_index(batch_op.f('idx_transfers_to_warehouse'))

    op.drop_table('transfers')
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ai_models_is_active'))
        batch_op.drop_index(batch_op.f('idx_ai_models_type'))

    op.drop_table('ai_models')
    op.drop_table('recipe_items_used')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_system_logs_created_at'))
        batch_op.drop_index(batch_op.f('idx_system_logs_level'))
        batch_op.drop_index(batch_op.f('idx_system_logs_module'))
        batch_op.drop_index(batch_op.f('idx_system_logs_user_id'))

    op.drop_table('system_logs')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cameras_ai_enabled'))
        batch_op.drop_index(batch_op.f('idx_cameras_status'))

    op.drop_table('cameras')
    op.drop_table('known_faces')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='low, medium, high, critical',
               existing_server_default=sa.text("'medium'::character varying"))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('camera_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='new, acknowledged, resolved, dismissed',
               existing_nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
        batch_op.alter_column('data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_alerts_camera_id'))
        batch_op.drop_index(batch_op.f('idx_alerts_created_at'))
        batch_op.drop_index(batch_op.f('idx_alerts_severity'))
        batch_op.drop_index(batch_op.f('idx_alerts_status'))
        batch_op.drop_index(batch_op.f('idx_alerts_type'))
        batch_op.drop_constraint(batch_op.f('alerts_inventory_item_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('alerts_production_run_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('alerts_resolved_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('alerts_camera_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('alerts_acknowledged_by_fkey'), type_='foreignkey')
        batch_op.drop_table_comment(
        existing_comment='System alerts and notifications'
    )

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_inventory_expiry'))
        batch_op.drop_index(batch_op.f('idx_inventory_product_id'))
        batch_op.drop_index(batch_op.f('idx_inventory_product_warehouse'))
        batch_op.drop_index(batch_op.f('idx_inventory_quantity'))
        batch_op.drop_index(batch_op.f('idx_inventory_warehouse_id'))
        batch_op.drop_constraint(batch_op.f('inventory_items_warehouse_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('inventory_items_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Stock items in warehouses'
    )
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('batch_number')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_order_items_order_id'))
        batch_op.drop_index(batch_op.f('idx_order_items_product_id'))
        batch_op.drop_constraint(batch_op.f('order_items_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Items within an order'
    )
        batch_op.drop_column('price')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, processing, completed, cancelled, shipped',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='unpaid, paid, partially_paid, refunded',
               existing_nullable=True,
               existing_server_default=sa.text("'unpaid'::character varying"))
        batch_op.drop_index(batch_op.f('idx_orders_created_by'))
        batch_op.drop_index(batch_op.f('idx_orders_customer_email'))
        batch_op.drop_index(batch_op.f('idx_orders_order_date'))
        batch_op.drop_index(batch_op.f('idx_orders_order_number'))
        batch_op.drop_index(batch_op.f('idx_orders_payment_status'))
        batch_op.drop_index(batch_op.f('idx_orders_status'))
        batch_op.drop_constraint(batch_op.f('orders_order_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('orders_created_by_fkey'), type_='foreignkey')
        batch_op.drop_table_comment(
        existing_comment='Customer orders'
    )
        batch_op.drop_column('updated_at')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('notes')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('production_lines', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='operational, stopped, maintenance',
               existing_server_default=sa.text("'operational'::character varying"))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('last_maintenance',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('next_maintenance',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_production_lines_product_id'))
        batch_op.drop_index(batch_op.f('idx_production_lines_status'))
        batch_op.drop_table_comment(
        existing_comment='Production lines for manufacturing'
    )
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('production_runs', schema=None) as batch_op:
        batch_op.alter_column('run_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('production_line_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='planned, in-progress, completed, stopped, cancelled',
               existing_server_default=sa.text("'planned'::character varying"))
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_production_runs_created_by'))
        batch_op.drop_index(batch_op.f('idx_production_runs_dates'))
        batch_op.drop_index(batch_op.f('idx_production_runs_line_id'))
        batch_op.drop_index(batch_op.f('idx_production_runs_product_id'))
        batch_op.drop_index(batch_op.f('idx_production_runs_run_number'))
        batch_op.drop_index(batch_op.f('idx_production_runs_status'))
        batch_op.drop_constraint(batch_op.f('production_runs_run_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('production_runs_created_by_fkey'), type_='foreignkey')
        batch_op.drop_table_comment(
        existing_comment='Production runs/batches'
    )
        batch_op.drop_column('updated_at')
        batch_op.drop_column('expected_duration')
        batch_op.drop_column('notes')
        batch_op.drop_column('actual_duration')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_products_category'))
        batch_op.drop_index(batch_op.f('idx_products_is_active'))
        batch_op.drop_index(batch_op.f('idx_products_name'))
        batch_op.drop_index(batch_op.f('idx_products_sku'))
        batch_op.drop_table_comment(
        existing_comment='Products for sale and manufacturing'
    )
        batch_op.drop_column('units_per_run')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('unit')
        batch_op.drop_column('production_time')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('recipe_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='The product being manufactured',
               existing_nullable=False)
        batch_op.alter_column('ingredient_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='The ingredient used',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_recipe_items_ingredient'))
        batch_op.drop_index(batch_op.f('idx_recipe_items_product'))
        batch_op.drop_constraint(batch_op.f('unique_recipe'), type_='unique')
        batch_op.drop_constraint(batch_op.f('recipe_items_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('recipe_items_ingredient_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Recipe for product manufacturing'
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='admin, inventory_staff, sales_staff, production_staff',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_role'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_table_comment(
        existing_comment='User authentication and authorization'
    )
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_login')

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='raw_materials, wholesale, detailed_sales, archive')
        batch_op.drop_table_comment(
        existing_comment='Warehouse locations and types'
    )
        batch_op.drop_column('current_usage')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('capacity')
        batch_op.drop_column('location')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_usage', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Warehouse locations and types',
        existing_comment=None
    )
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='raw_materials, wholesale, detailed_sales, archive')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'User authentication and authorization',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               comment='admin, inventory_staff, sales_staff, production_staff',
               existing_nullable=False)

    with op.batch_alter_table('recipe_items', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Recipe for product manufacturing',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipe_items_ingredient_id_fkey'), 'products', ['ingredient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('recipe_items_product_id_fkey'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_recipe'), ['product_id', 'ingredient_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_recipe_items_product'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_recipe_items_ingredient'), ['ingredient_id'], unique=False)
        batch_op.alter_column('ingredient_id',
               existing_type=sa.VARCHAR(length=36),
               comment='The ingredient used',
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.VARCHAR(length=36),
               comment='The product being manufactured',
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('production_time', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=20), server_default=sa.text("'units'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('units_per_run', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Products for sale and manufacturing',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_products_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_category'), ['category'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('production_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('actual_duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expected_duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Production runs/batches',
        existing_comment=None
    )
        batch_op.create_foreign_key(batch_op.f('production_runs_created_by_fkey'), 'users', ['created_by'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('production_runs_run_number_key'), ['run_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_production_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_production_runs_run_number'), ['run_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_production_runs_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_production_runs_line_id'), ['production_line_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_production_runs_dates'), ['start_date', 'completion_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_production_runs_created_by'), ['created_by'], unique=False)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='planned, in-progress, completed, stopped, cancelled',
               existing_server_default=sa.text("'planned'::character varying"))
        batch_op.alter_column('production_line_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('run_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('production_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Production lines for manufacturing',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_production_lines_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_production_lines_product_id'), ['product_id'], unique=False)
        batch_op.alter_column('next_maintenance',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('last_maintenance',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='operational, stopped, maintenance',
               existing_server_default=sa.text("'operational'::character varying"))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Customer orders',
        existing_comment=None
    )
        batch_op.create_foreign_key(batch_op.f('orders_created_by_fkey'), 'users', ['created_by'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('orders_order_number_key'), ['order_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_order_number'), ['order_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_customer_email'), ['customer_email'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_created_by'), ['created_by'], unique=False)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               comment='unpaid, paid, partially_paid, refunded',
               existing_nullable=True,
               existing_server_default=sa.text("'unpaid'::character varying"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, processing, completed, cancelled, shipped',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('order_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.create_table_comment(
        'Items within an order',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_items_order_id_fkey'), 'orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_items_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Stock items in warehouses',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('inventory_items_product_id_fkey'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('inventory_items_warehouse_id_fkey'), 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_inventory_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventory_quantity'), ['quantity'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventory_product_warehouse'), ['product_id', 'warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventory_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventory_expiry'), ['expiry_date'], unique=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_table_comment(
        'System alerts and notifications',
        existing_comment=None
    )
        batch_op.create_foreign_key(batch_op.f('alerts_acknowledged_by_fkey'), 'users', ['acknowledged_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('alerts_camera_id_fkey'), 'cameras', ['camera_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('alerts_resolved_by_fkey'), 'users', ['resolved_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('alerts_production_run_id_fkey'), 'production_runs', ['production_run_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('alerts_inventory_item_id_fkey'), 'inventory_items', ['inventory_item_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_alerts_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerts_camera_id'), ['camera_id'], unique=False)
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='new, acknowledged, resolved, dismissed',
               existing_nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
        batch_op.alter_column('camera_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='low, medium, high, critical',
               existing_server_default=sa.text("'medium'::character varying"))

    op.create_table('known_faces',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(uuid_generate_v4())::text'), autoincrement=False, nullable=False),
    sa.Column('person_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('face_encoding', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('known_faces_pkey')),
    comment='Known faces database for AI face recognition'
    )
    op.create_table('cameras',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(uuid_generate_v4())::text'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('port', sa.INTEGER(), server_default=sa.text('554'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True, comment='active, inactive, error, maintenance'),
    sa.Column('ai_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('ai_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_active', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'error'::character varying, 'maintenance'::character varying]::text[])", name=op.f('cameras_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('cameras_pkey')),
    comment='Camera feeds for monitoring'
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cameras_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_cameras_ai_enabled'), ['ai_enabled'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(uuid_generate_v4())::text'), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('module', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("level::text = ANY (ARRAY['INFO'::character varying, 'WARNING'::character varying, 'ERROR'::character varying, 'DEBUG'::character varying]::text[])", name=op.f('system_logs_level_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('system_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_logs_pkey')),
    comment='System activity logs'
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_system_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_system_logs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('idx_system_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('idx_system_logs_created_at'), ['created_at'], unique=False)

    op.create_table('recipe_items_used',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(uuid_generate_v4())::text'), autoincrement=False, nullable=False),
    sa.Column('production_run_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('quantity_used', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), server_default=sa.text("'units'::character varying"), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantity_used > 0::numeric', name=op.f('quantity_used_positive')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['products.id'], name=op.f('recipe_items_used_ingredient_id_fkey')),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_runs.id'], name=op.f('recipe_items_used_production_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('recipe_items_used_pkey')),
    comment='Track ingredients used in production runs'
    )
    op.create_table('ai_models',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(uuid_generate_v4())::text'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='sales_forecast, anomaly_detection, face_recognition, production_optimization, inventory_prediction'),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('model_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('last_trained', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("type::text = ANY (ARRAY['sales_forecast'::character varying, 'anomaly_detection'::character varying, 'face_recognition'::character varying, 'production_optimization'::character varying, 'inventory_prediction'::character varying]::text[])", name=op.f('ai_models_type_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_models_pkey')),
    comment='AI/ML models information'
    )
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ai_models_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('idx_ai_models_is_active'), ['is_active'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(uuid_generate_v4())::text'), autoincrement=False, nullable=False),
    sa.Column('from_warehouse_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('to_warehouse_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True, comment='pending, in_transit, completed, cancelled'),
    sa.Column('transfer_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'in_transit'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])", name=op.f('transfers_status_check')),
    sa.CheckConstraint('from_warehouse_id::text <> to_warehouse_id::text', name=op.f('different_warehouses')),
    sa.CheckConstraint('quantity > 0', name=op.f('quantity_positive_transfer')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('transfers_created_by_fkey')),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], name=op.f('transfers_from_warehouse_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('transfers_product_id_fkey')),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], name=op.f('transfers_to_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transfers_pkey')),
    comment='Inventory transfers between warehouses'
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_transfers_to_warehouse'), ['to_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_transfers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_transfers_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_transfers_from_warehouse'), ['from_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_transfers_dates'), ['transfer_date', 'completed_date'], unique=False)

    # ### end Alembic commands ###
